[about]
name = "djdjz"
avatar = "djdjz.jpg"
hobbies = ["ğŸ¨ Desgin", "ğŸ’» Programming", "ğŸ¸ Badminton"]
skills = ["C#", "Rust", "TypeScript", "Vue"]

[social]
github = "djdjz7"
website = "https://djdjz7.top"


