[about]
name = "åƒä¸€åˆ‡çŒ«"
avatar = "hzh.png"
hobbies = ["ğŸ± Cat", "ğŸ§ Linux", "ğŸ¥˜ Cooking"]
skills = ["Linux", "Golang", "Rust", "TypeScript"]

[social]
github = "holgerhuo"
website = "https://holger.one"


